### ISSUE TITLE
Implement checkpointing

### ISSUE THREAD

**Issue by xflouris** [xflouris/bpp#39]
Implement an option called 'checkpoint' in the control file, which takes either one or two integer parameters, and one string parameter:

1. If one integer parameter `x` is specified then only one checkpoint is set after `x` MCMC steps.

2. If two integer parameters `x` and `y` are specified, then set a checkpoint after `x` MCMC steps, and then after every `y` steps.

3. The string parameter `z` is the name of the checkpoint file.

The function will save in `z` all 'important' variables of the program in binary format such as not to lose precision on floating-point numbers. `Important' are variables whose content cannot be re-constructed using other stored information, and include the MCMC chain variables + random number generator. The checkpoint record will also include a CRC/checksum entry, to make sure the checkpoint was written correctly (e.g. in case server/cluster wall-time occurs while writing the checkpoint).

The checkpoint will resume by using a `--resume z` switch, which will trim the steps logged in the MCMC file after the checkpoint, and continue from the step after the checkpoint.

Another (simpler) way of checkpointing is storing the whole memory layout, i.e. a memory dump. However, that would have a huge space footprint, and will slow down execution considerably.

**Comment by ziheng-yang** [comment]
Dear Tomas,
This looks fine to me.  It should be much better than memory dump.   Did you confirm that you get the same mcmc sample file whether or not you use breakpointing.
 I didn’t save the random number (I forgot why) so that the two would generate different mcmc sample files (after the break point ). I think that’s the only difference.
Best,
Ziheng



On 17 Oct 2017, at 12:23, Tomas Flouri <notifications@github.com<mailto:notifications@github.com>> wrote:


Implement an option called 'checkpoint' in the control file, which takes either one or two integer parameters, and one string parameter:

  1.  If one integer parameter x is specified then only one checkpoint is set after x MCMC steps.

  2.  If two integer parameters x and y are specified, then set a checkpoint after x MCMC steps, and then after every y steps.

  3.  The string parameter z is the name of the checkpoint file.

The function will save in z all 'important' variables of the program in binary format such as not to lose precision on floating-point numbers. `Important' are variables whose content cannot be re-constructed using other stored information, and include the MCMC chain variables + random number generator. The checkpoint record will also include a CRC/checksum entry, to make sure the checkpoint was written correctly (e.g. in case server/cluster wall-time occurs while writing the checkpoint).

The checkpoint will resume by using a --resume z switch, which will trim the steps logged in the MCMC file after the checkpoint, and continue from the step after the checkpoint.

Another (simpler) way of checkpointing is storing the whole memory layout, i.e. a memory dump. However, that would have a huge space footprint, and will slow down execution considerably.

**Comment by xflouris** [comment]
Add the following switches:
* `--resume X` to resume using checkpoint X
* `--reset-rng X` to reset RNG to value X when resuming a checkpoint
* `--show X` to show information regarding checkpoint file X

The checkpoint file should consist of roughly the following information:
Magic : 4B  (set to BPPX)
Version part MAJOR : 4B
Version part MINOR : 4B
Version part PATCH : 4B
Checksum hash : 4B
RNG value : 4B
Number of sections : 4B
Reserved: 40 B
Section lengths : # Sections x 4B

For current BPP version we will use four sections:

Section 1 - Configuration
-------------------------
Seed : 4B
Seqfile : zero-terminated string
Imapfile: zero-terminated string
outfile: zero-terminated string
mcmcfile : zero-terminated string
speciesdelimtation : 4B
speciestree : 1B + 3x64-bit : 25B
speciesmodelprior : 1B
species&tree : 32-bit Number of species + # Species  zero-terminated strings (species labels)
usedata : 1B
nloci : 4B
cleandata : 1B
thetaprior : 1B + 2x64-bit : 17B
tauprior : 2x64-bit : 16B
finetune : 1B + 5x64-bit : 41B
diploid : Number of species x 1B
burnin : 64-bit 
sampfreq : 64-bit
nsample : 64-bit

Section 2 - Locus information
-----------------------------
/* This is a hugely incomplete list */
Number of sites
Number of rate matrices
Number of probability matrices
Number of rate categories
Number of scale buffers
Attributes : 32-bit
Memory alignment : 32-bit
Pattern weights array
diploid : 1B

if (diploid)
diploid mapping
diploid resolution count
unphased length

Repeat for each locus


Section 3 - Species tree status
-------------------------------
Species tree nodes indices postorder
Species tree nodes lengths postorder
Species tree nodes thetas postorder
Species tree nodes taus postorder
Species tree nodes support postorder
Species tree node number of coalescent events
Species tree logpr contribution
Species tree root_age

Section 4 - Gene tree status
----------------------------
Gene tree nodes indices postorder
Gene tree nodes lengths postorder
Gene tree node ages postorder
Gene tree node clv indices postorder
Gene tree node pmatrix indices postorder
Gene tree node scaler indices postorder
Gene tree logl
Gene tree logpr
Repeat for each gene tree

**Comment by xflouris** [comment]
finished
